#!/usr/bin/env python3
"""Create a tiny synthetic file with the inoisy+ HDF5 layout.

This is a queue-delay fallback for the visualization lesson, not output from
the inoisy+ solver. The processed fallback is produced separately by running
the unmodified upstream emissivity converter on this file.
"""

from __future__ import annotations

from pathlib import Path

import h5py
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
OUT = (
    ROOT
    / "tutorials"
    / "05-visualization-postprocessing"
    / "data"
    / "sample_inoisy4d_lowres.h5"
)


def main() -> None:
    nt, nx, ny, nz = 8, 16, 16, 16
    x0start, x0end = 0.0, 40.0
    x1start = x2start = x3start = -20.0
    x1end = x2end = x3end = 20.0
    dx0 = (x0end - x0start) / nt
    dx1 = (x1end - x1start) / nx
    dx2 = (x2end - x2start) / ny
    dx3 = (x3end - x3start) / nz

    x = x1start + dx1 * (np.arange(nx) + 0.5)
    y = x2start + dx2 * (np.arange(ny) + 0.5)
    z = x3start + dx3 * (np.arange(nz) + 0.5)
    xx, yy, zz = np.meshgrid(x, y, z, indexing="ij")

    rng = np.random.default_rng(20260819)
    raw = np.empty((nt, nx, ny, nz), dtype=np.float64)
    for it in range(nt):
        phase = 2.0 * np.pi * it / nt
        coherent = (
            np.sin(0.22 * xx + phase)
            + 0.7 * np.cos(0.18 * yy - 0.5 * phase)
            + 0.5 * np.sin(0.16 * zz + 0.3 * phase)
        )
        envelope = np.exp(-0.5 * ((np.sqrt(xx**2 + yy**2) - 10.0) / 8.0) ** 2)
        raw[it] = envelope * coherent + 0.25 * rng.standard_normal((nx, ny, nz))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with h5py.File(OUT, "w") as handle:
        data = handle.create_group("data")
        data.create_dataset("data_raw", data=raw, compression="gzip")
        data.create_dataset("lc_raw", data=raw.sum(axis=(1, 2, 3)))

        params = handle.create_group("params")
        scalars = {
            "x0start": x0start,
            "x0end": x0end,
            "x1start": x1start,
            "x1end": x1end,
            "x2start": x2start,
            "x2end": x2end,
            "x3start": x3start,
            "x3end": x3end,
            "dx0": dx0,
            "dx1": dx1,
            "dx2": dx2,
            "dx3": dx3,
            "avg_raw": raw.mean(),
            "var_raw": raw.var(ddof=1),
            "torus_r0": 10.0,
            "torus_ar": 8.0,
            "torus_az": 5.0,
            "jet_width": 2.5,
            "jet_opening": 0.3,
            "sigma_d": 0.2,
            "sigma_j": 0.2,
            "jdisk0": 1.0,
            "jjet0": 1.0,
        }
        integers = {
            "npk": 1,
            "npl": 1,
            "npj": 1,
            "npi": 1,
            "nk": nt,
            "nl": nx,
            "nj": ny,
            "ni": nz,
            "seed": 20260819,
        }
        for name, value in scalars.items():
            params.create_dataset(name, data=float(value))
        for name, value in integers.items():
            params.create_dataset(name, data=int(value))
        params.attrs["course_fallback"] = True
        params.attrs["provenance"] = (
            "Synthetic schema-compatible fallback; not generated by inoisy+."
        )

    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
